# Generated by Django 5.1.7 on 2025-03-30 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_end_date_alter_event_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='registration_date',
            new_name='registered_at',
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
    ]
