# Generated by Django 5.1.7 on 2025-04-09 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_registration_date_participant_registered_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='registered_at',
            new_name='registration_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата и время начала'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Электронная почта'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('email', 'event')},
        ),
    ]
